[package]
name = "gmod-bson"
authors = ["kithf"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
strip = true
lto = true

[dependencies]
gmod = "16.0"
mongodb = "2.0"
serde_json = "1.0"
chrono = "0.4"